### PR TITLE
introduced autojoining snippet from matrix-js-sdk

### PR DESCRIPTION
**Pull request by DrSwaggos**
changes:

- added autojoining snippet from [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk)
- updated dependencies

### CODE REVIEW

**Comment by oelison** [comment]
Thank you for your pull request. Could you split your changes and your reformatting into two commits?

**Comment by DrSwaggos** [comment]
The reformatting was done by my editor automagically. Therefore, I would have to undo the formatting by hand. Is this a major problem?

**Comment by oelison** [comment]
The problem is, that I can't see the real changes.

**Comment by oelison** [comment]
I will try to review it on my PC later. So don't change anything then.

**Comment by oelison** [comment]
Hi @DrSwaggos,
I have worked in your branch to have your commit in the history. I have added a bit, that what is needed to have a green build and that auto Join could be enabled, when needed. I think auto join should be dangerous for a bot. The readme also need some updates. I will do it, when you like this branch now, too.

**Comment by oelison** [comment]
@DrSwaggos Thank you.

**Comment by DrSwaggos** [comment]
Are you also working on encryption support?

**Pull request merged**
